### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by gdude2002** [Kotlin-Discord/meta#1]
This is everything we need to do before we can start our launch. Let's get to it!

---

## Bot Tasks

- [x] User verification (https://github.com/Kotlin-Discord/bot/issues/2)
    - [x] Basic implementation
    - [x] Logging
    - [x] Send DM to user
- [ ] Announcements role subscription
    - [x] Commands to assign/unassign role
    - [ ] Restore this role if someone rejoins
- [x] Filtering system
- [ ] Anti-spam system (https://github.com/Kotlin-Discord/bot/pull/8) 
- [x] Event logging system (https://github.com/Kotlin-Discord/bot/issues/3 / https://github.com/Kotlin-Discord/bot/pull/11)
    - [x] Basic user event logging
    - [x] Remember to log account creation times and tag new accounts
- [ ] Moderation commands (https://github.com/Kotlin-Discord/bot/issues/1)
- [ ] Clean command (https://github.com/Kotlin-Discord/bot/issues/1 / https://github.com/Kotlin-Discord/bot/pull/10)
- [x] Remove test extension, or at least don't load it

## Site Tasks

- [x] Working database setup (https://github.com/Kotlin-Discord/database/pull/1)
- [x] Basic authenticated API
    - [x] Infractions
    - [x] Users
    - [ ] Channels
    - [x] Roles
- [x] Resources pages
- [ ] Community tips page (how to make the most of the community)

## GitHub

- [ ] Look over permissions and teams
- [ ] Double-check all webhooks are in place
- [ ] Ensure that all repositories have a full set of appropriate documentation
	* Code of conduct
	* Contributor guidelines
	* Documentation
	* Issue templates
	* Maven coordinates

## Server Tasks

- [x] Permissions
    - [x] Clear all perms from all roles and assign them specifically as needed - make it additive, in other words
    - [x] Only developers should be able to talk and react outside of #verification
    - [x] All public channels should be visible in lurk mode
    - [x] Development category
        - [x] #dev-bot-testing and #dev-core shouldn't be public
- [x] Proxy all dependencies through our Nexus
- [x] Sentry
- [x] ModMail bot
- [x] Role colours
- [x] Channel organisation
    - [x] Off-topic channels should probably be right below the info channels,
          as is the convention on Discord
- [x] Staff policy documents
    - [x] Helper policy
    - [x] Moderation policy
    - [x] ModMail usage policy
- [x] Pride branding
- [x] Design and apply server banner

Pre-flight
==========

- [ ] Have someone join with an alt and check:
    - [ ] Verification flow
    - [ ] ModMail
    - [ ] Channel permissions

Post-launch tasks
=================

- [ ] Announcements on site
- [ ] Automated announcements system based on site posts
- [ ] Come up with a set of emojis
- [ ] Solve the audit logging problem
- [ ] Codeblock warning feature
